### ISSUE TITLE
getpack.sh provided versions for dependencies don't exist.  Update does not work 

### ISSUE THREAD

**Issue by utsavZebra** [warrenwoolseyiii/Arduino-SAMD20#8]
The versions specified for CMSIS and SAMD20 DFP no longer exist on the website. I updated them to the latest ones and the files dont seem to be there despite the script extracting it

**Comment by warrenwoolseyiii** [comment]
This should be resolved in the latest version 9f0605d02b8c626b7192e2f4872d621dc4364022.

I would run `make clean-all-toolchains` and then `make distclean` and then pull the latest version and make a fresh build
